### ISSUE TITLE
[SECURITY]: Make API-keys Environment Variables 

### ISSUE THREAD

**Issue by Vyvy-vi** [nishchaysinha/weatherapp#1]
It's best to not include them on your repo as ppl get all sorts of weird ideas.
(yeah I know just weather api keys, but still- call it a best practice or something idk)

**Comment by nishchaysinha** [comment]
> It's best to not include them on your repo as ppl get all sorts of weird ideas.
> (yeah I know just weather api keys, but still- call it a best practice or something idk)

Yeah ik I'll be creating a database for it soon so won't be necessary it's here for convenience as of now
